# $FreeBSD: head/lib/clang/libllvmsparcinfo/Makefile 276479 2014-12-31 20:31:32Z dim $

.include <bsd.own.mk>

LIB=	llvmsparcinfo

SRCDIR=	lib/Target/Sparc/TargetInfo
INCDIR=	lib/Target/Sparc
SRCS=	SparcTargetInfo.cpp

TGHDRS=	SparcGenInstrInfo \
	SparcGenRegisterInfo \
	SparcGenSubtargetInfo

.include "../clang.lib.mk"
